version: "3"
services:
  web:
    image: ebm1718travis/linkapp:latest
    environment:
      - MONGODB_URI=mongodb://mongodb/node-auth
    networks:
      local:
      ebm-filrouge:
        aliases:
          - linkapp
  mongodb:
    image: mongo
    networks:
      - linkapp
networks:
  local:
  ebm-filrouge:
    external: true
