version: "3"
services:
  web:
    image: ebm1718travis/linkapp:latest
    environment:
      - MONGODB_URI=mongodb://mongodb/node-auth
      - SEED_USERNAME=root
      - SEED_PASSWORD=root
    networks:
      local:
      ebm-filrouge:
        aliases:
          - linkapp
  mongodb:
    image: mongo
    networks:
      - linkapp
    volumes:
      - mongo-volume:/data/db
networks:
  local:
  ebm-filrouge:
    external: true
volumes:
  mongo-volume:
